#!/bin/bash

source ./00_preprocessing

v_Package_name='vim'
v_Package_version='9.1.1255'

v_Package_archive="${PWD}/${v_Package_name}-${v_Package_version}.tar.gz"

[ -f "${v_Package_archive}" ] || wget --continue --output-document="${v_Package_archive}" "https://github.com/vim/vim/archive/refs/tags/v${v_Package_version}.tar.gz"

cd "${v_Build_Dir}" || exit 1

export CFLAGS="-static -Os"
export CFLAGS="${CFLAGS} -I${v_Prefix_Dir}/include"
export LDFLAGS="-L${v_Prefix_Dir}/lib -static"

v_Package_dir="${v_Package_name}-${v_Package_version}"

[ -d "${v_Package_dir}" ] && rm -rf "${v_Package_dir}"

tar -xf "${v_Package_archive}"

cd "${v_Package_dir}"

v_Package_Prefix="${v_Prefix_Dir}/${v_Package_name}" 

[ -d "${v_Package_Prefix}" ] && rm -rf "${v_Package_Prefix}" 

LIBS="-lncursesw" ./configure --prefix="${v_Package_Prefix}" \
	    --host="${v_Host_Platform}" \
	    --build="${v_Build_Platform}" \
	    --with-features=normal

make -j2
make STRIP="${v_Strip_Program}" install ; echo $?

mkdir -p "${v_Release_Dir}"
cp --no-dereference "${v_Package_Prefix}/bin/${v_Package_name}"* "${v_Release_Dir}"
