#!/bin/bash

source ./00_preprocessing

v_Package_name='libmd'
v_Package_version='1.1.0'

v_Package_archive="${PWD}/${v_Package_name}-${v_Package_version}.tar.gz"

wget --continue --output-document="${v_Package_archive}" "https://archive.hadrons.org/software/libmd/libmd-${v_Package_version}.tar.xz"

cd "${v_Build_Dir}" || exit 1

v_Package_dir="${v_Package_name}-${v_Package_version}"

[ -d "${v_Package_dir}" ] && rm -rf "${v_Package_dir}"

tar -xf "${v_Package_archive}"

cd "${v_Package_dir}"

export CFLAGS="-static -Os"
export CFLAGS="${CFLAGS} -I${v_Prefix_Dir}/include"
export LDFLAGS="-L${v_Prefix_Dir}/lib -static"

./configure --prefix="${v_Prefix_Dir}/bsd" \
	    --host=arm-linux-musleabihf \
	    --build=x86_64-pc-linux-gnu

make -j2
make install && echo $?
