#!/bin/bash

source /etc/profile.d/arm-linux-musleabihf-cross.sh

source ./0_preprocessing

v_Package_name='xxHash'
v_Package_version='0.8.2'

v_Package_archive="${PWD}/${v_Package_name}-${v_Package_version}.tar.gz"

wget --continue --output-document="${v_Package_archive}" "https://github.com/Cyan4973/xxHash/archive/refs/tags/v${v_Package_version}.tar.gz"

cd "${v_Build_Dir}" || exit 1

v_Package_dir="${v_Package_name}-${v_Package_version}"

[ -d "${v_Package_dir}" ] && rm -rf "${v_Package_dir}"

tar -xf "${v_Package_archive}"

cd "${v_Package_dir}"

# export CFLAGS="-static"
#export CFLAGS="${CFLAGS} -Os"
export CFLAGS="${CFLAGS} -I${v_Prefix_Dir}/include"
export CFLAGS="${CFLAGS} --sysroot=${v_Sysroot}"
# export LDFLAGS="-static"
export LDFLAGS="${LDFLAGS} -L${v_Prefix_Dir}/lib"
export LDFLAGS="${LDFLAGS} --sysroot=${v_Sysroot}"

export CC="${v_Host_Platform}-gcc"
#export LD="${v_Host_Platform}-ld"

make DISPATCH="0" prefix="${v_Prefix_Dir}" CC="${CC}" LD="${LD}" CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}" -j1
# make prefix="${v_Prefix_Dir}" CC="${CC}" LD="${LD}" CFLAGS="${CFLAGS}" LDFLAGS="${LDFLAGS}" install ; echo $?
