#!/bin/bash

source ./0_preprocessing

v_Package_name='rsync'
v_Package_version='3.4.1'

v_Package_archive="${PWD}/${v_Package_name}-${v_Package_version}.tar.gz"

wget --continue --output-document="${v_Package_archive}" "https://github.com/RsyncProject/rsync/archive/refs/tags/v${v_Package_version}.tar.gz"

cd "${v_Build_Dir}" || exit 1

v_Package_dir="${v_Package_name}-${v_Package_version}"

[ -d "${v_Package_dir}" ] && rm -rf "${v_Package_dir}"

tar -xf "${v_Package_archive}"

cd "${v_Package_dir}"

v_Package_Prefix="${v_Prefix_Dir}/${v_Package_name}" 

[ -d "${v_Package_Prefix}" ] && rm -rf "${v_Package_Prefix}" 

export CFLAGS="-static -Os"
export CFLAGS="${CFLAGS} -I${v_Prefix_Dir}/include"
export LDFLAGS="-L${v_Prefix_Dir}/lib -static"

./configure --prefix="${v_Package_Prefix}" \
	    --host=arm-linux-musleabihf \
	    --build=x86_64-pc-linux-gnu \
	    --disable-md2man \
	    --disable-zstd \
	    --disable-lz4 \
	    --disable-openssl \
    	    --disable-xxhash


make -j2
make INSTALLCMD="install -c --strip-program=${v_Strip_Program}" install-strip ; echo "make exited with status: ${?}"
mkdir -p "${v_Release_Dir}"
cp "${v_Package_Prefix}/bin/"rsync* "${v_Release_Dir}"
