#!/bin/bash

source ./00_preprocessing

v_Package_name='libdaemon'
v_Package_version='0.14'

v_Package_archive="${PWD}/${v_Package_name}-${v_Package_version}.tar.gz"

[ -f "${v_Package_archive}" ] || wget --continue --output-document="${v_Package_archive}" "http://0pointer.de/lennart/projects/libdaemon/libdaemon-${v_Package_name}.tar.gz"

cd "${v_Build_Dir}" || exit 1

v_Package_dir="${v_Package_name}-${v_Package_version}"

[ -d "${v_Package_dir}" ] && rm -rf "${v_Package_dir}"

tar -xf "${v_Package_archive}"

cd "${v_Package_dir}"

export CFLAGS="-static -Os"
export CFLAGS="${CFLAGS} -I${v_Prefix_Dir}/include"
export LDFLAGS="-L${v_Prefix_Dir}/lib -static"

curl -L https://git.savannah.gnu.org/cgit/config.git/plain/config.guess -o config.guess
curl -L https://git.savannah.gnu.org/cgit/config.git/plain/config.sub -o config.sub

./configure --prefix="${v_Prefix_Dir}" \
	    --host="${v_Host_Platform}" \
	    --build="${v_Build_Platform}" \
	    --disable-lynx \
	    --disable-examples \
	    ac_cv_func_setpgrp_void=yes

make -j2
make install && echo $?
