#!/bin/bash

source ./00_preprocessing

v_Package_name='libatomic_ops'
v_Package_version='7.8.2'


v_Package_archive="${PWD}/${v_Package_name}-${v_Package_version}.tar.gz"

[ -f "${v_Package_archive}" ] || wget --continue --output-document="${v_Package_archive}" "https://github.com/ivmai/libatomic_ops/releases/download/v${v_Package_version}/libatomic_ops-${v_Package_version}.tar.gz"

cd "${v_Build_Dir}" || exit 1

export CFLAGS="-static -Os"
export CFLAGS="${CFLAGS} -I${v_Prefix_Dir}/include"
export LDFLAGS="-L${v_Prefix_Dir}/lib -static"

v_Package_dir="${v_Package_name}-${v_Package_version}"

[ -d "${v_Package_dir}" ] && rm -rf "${v_Package_dir}"

tar -xf "${v_Package_archive}"

cd "${v_Package_dir}"

./configure --prefix="${v_Prefix_Dir}" \
	    --host=arm-linux-musleabihf \
	    --build=x86_64-pc-linux-gnu

make -j1
make install && echo $?
